### PR TITLE
Cmake reverted

### PR DESCRIPTION
**Pull request by mitjap**
I reverted entire `cmake` branch to state before _Feb 24 2016_. Since that day branch does not compile on windows anymore. I think something weird happend since history is lost/rewritten. Last working commit is on _Dec 15 2015_.

### CODE REVIEW

**Comment by andre-schulz** [comment]
Thanks for the report.
Can you please describe what exactly doesn't compile, which compiler you are using and what is the error message that you get?
Is it the `constexpr` keyword in [libs/math/vector.h](https://github.com/andre-schulz/mve/blob/master/libs/math/vector.h#L119)?
Regarding the lost history; that's unfortunately "normal" because I rebase the cmake branch on the master branch of Simon's repository whenever he commits new code and I then force push the new commits plus the rebased patches.

**Comment by mitjap** [comment]
Yes, the problem is with `constexpr` in `...vector.h`. I did not investigate further as I thought that this was an accidental mistake. I'm running VS2013 (VC12).

**Comment by andre-schulz** [comment]
Well, it's not a mistake because I'm currently working with Simon on integrating cascade hashing into MVE and that code depends on `math::Vector<T,N>::dim()` being a `constexpr`. Unfortunately, VS2013 does not support `constexpr` at all except for the [November 2013 CTP](https://blogs.msdn.microsoft.com/vcblog/2013/11/18/announcing-the-visual-c-compiler-november-2013-ctp/). I tried compiling with that version but there were errors during linking and I didn't investigate further. This means that currently the solution is to use Visual Studio 2015 which fully supports `constexpr`. Actually, because I can't think of a simple workaround for the `constexpr` issue this will most likely mean that MVE will only be compilable on Windows with Visual Studio 2015. But, hopefully, this shouldn't be much of an issue because Microsoft offers Visual Studio 2015 Community Edition for free.

**Comment by mitjap** [comment]
Thank you for extensive explanation.

**Comment by andre-schulz** [comment]
I've investigated a bit further and thanks to a friend of mine I've found a workaround for the `constexpr` issue. But, unfortunately, there is also another issue when using VS2013 because it doesn't support non-static in-class member initialization (see [libs/sfm/matching_base.h)](https://github.com/andre-schulz/mve/blob/master/libs/sfm/matching_base.h#L27). So, if for whatever reason you still want or need to use VS2013, try this [patch](https://gist.github.com/andre-schulz/bab4e8ed092b3dfef511).
Beware though, these changes will not be committed to my or the official repository and if you want to use newer changes/features it will be the easiest to use VS2015 as more C++11 features will be used over time.

**Pull request closed without merging**
